FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .
RUN pip install -r requirements.txt -t .

COPY app/ app/

# Handler: module.function
CMD ["app.lambda_handler.handler"]

